create extension if not exists pgcrypto;

create table if not exists public.buyers (
  id uuid primary key default gen_random_uuid(),
  auth_id uuid unique references auth.users(id) on delete cascade,
  email text unique,
  name text,
  phone text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sellers (
  id bigint generated by default as identity primary key,
  auth_id uuid unique references auth.users(id) on delete set null,
  email text,
  name text not null,
  seller text,
  region text,
  category text,
  tier text not null default 'standard' check (tier in ('standard', 'gold', 'platinum')),
  wa text,
  lat numeric(10,7),
  lng numeric(10,7),
  data jsonb not null default '{}'::jsonb,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_code text unique,
  seller_id bigint references public.sellers(id) on delete set null,
  buyer_id uuid references auth.users(id) on delete set null,
  buyer_name text,
  items jsonb not null default '[]'::jsonb,
  subtotal numeric(10,2) not null default 0,
  total numeric(10,2) not null default 0,
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

create table if not exists public.messages (
  id uuid primary key default gen_random_uuid(),
  sender_id uuid references auth.users(id) on delete set null,
  recipient_id uuid references auth.users(id) on delete set null,
  seller_id bigint references public.sellers(id) on delete set null,
  subject text,
  body text,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  title text not null,
  body text not null,
  type text not null default 'system',
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_buyers_updated_at on public.buyers;
create trigger trg_buyers_updated_at
before update on public.buyers
for each row execute function public.touch_updated_at();

drop trigger if exists trg_sellers_updated_at on public.sellers;
create trigger trg_sellers_updated_at
before update on public.sellers
for each row execute function public.touch_updated_at();

alter table public.buyers enable row level security;
alter table public.sellers enable row level security;
alter table public.orders enable row level security;
alter table public.messages enable row level security;
alter table public.notifications enable row level security;

drop policy if exists buyers_select_own on public.buyers;
create policy buyers_select_own on public.buyers
for select using (auth.uid() = auth_id);

drop policy if exists buyers_upsert_own on public.buyers;
create policy buyers_upsert_own on public.buyers
for insert with check (auth.uid() = auth_id);

drop policy if exists buyers_update_own on public.buyers;
create policy buyers_update_own on public.buyers
for update using (auth.uid() = auth_id) with check (auth.uid() = auth_id);

drop policy if exists sellers_public_read on public.sellers;
create policy sellers_public_read on public.sellers
for select using (active = true);

drop policy if exists sellers_update_own on public.sellers;
create policy sellers_update_own on public.sellers
for update using (auth.uid() = auth_id) with check (auth.uid() = auth_id);

drop policy if exists sellers_insert_own on public.sellers;
create policy sellers_insert_own on public.sellers
for insert with check (auth.uid() = auth_id);

drop policy if exists orders_insert_auth on public.orders;
create policy orders_insert_auth on public.orders
for insert with check (auth.role() = 'authenticated');

drop policy if exists orders_select_related on public.orders;
create policy orders_select_related on public.orders
for select using (
  auth.uid() = buyer_id
  or exists (select 1 from public.sellers s where s.id = orders.seller_id and s.auth_id = auth.uid())
);

drop policy if exists messages_insert_auth on public.messages;
create policy messages_insert_auth on public.messages
for insert with check (auth.role() = 'authenticated');

drop policy if exists messages_select_related on public.messages;
create policy messages_select_related on public.messages
for select using (auth.uid() = sender_id or auth.uid() = recipient_id);

drop policy if exists notifications_select_own on public.notifications;
create policy notifications_select_own on public.notifications
for select using (auth.uid() = user_id);

drop policy if exists notifications_update_own on public.notifications;
create policy notifications_update_own on public.notifications
for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

create index if not exists idx_sellers_auth on public.sellers(auth_id);
create index if not exists idx_sellers_active on public.sellers(active);
create index if not exists idx_orders_seller on public.orders(seller_id);
create index if not exists idx_messages_recipient on public.messages(recipient_id, is_read);
